language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - composer self-update
    - composer install --dev --prefer-dist --no-interaction

script: phpunit --coverage-text
